<a href="https://colab.research.google.com/github/kaiiiiiyeee/data-science-toolkit/blob/main/T3_WIX1007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [3]:
n1 = np.array([[1,2],[3,4]])
print(n1)

[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [5]:
n2 = np.random.random((3,4))
print(n2)

[[0.21555718 0.10502572 0.54954325 0.63613278]
 [0.25893057 0.17541315 0.39899497 0.75748869]
 [0.45057333 0.89015174 0.5177006  0.36163745]]


3. Create a numpy array of ones and a numpy array of zeroes

In [6]:
n3 = np.zeros((2,2))
n4 = np.ones((2,2))
print(n3)
print(n4)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


4. Create a random numpy array of size 6 x 3 and transpose it

In [7]:
n5 = np.random.random((6,3))
transposed_5 = n5.T
print(transposed_5)


[[0.17651309 0.71468188 0.391524   0.48478251 0.37049824 0.2117349 ]
 [0.56010053 0.79297946 0.22787541 0.54642575 0.65615447 0.40356843]
 [0.82586636 0.33463289 0.39040891 0.02069673 0.31864396 0.82740974]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
n = 3
p = 4
m = 2
n6 = np.random.random((n,p))
n7 = np.random.random((p,m))
dot_product = n6 @ n7
print(n6)
print(n7)
print(dot_product)


[[0.72616727 0.83638405 0.44998361 0.96604544]
 [0.26298314 0.30905725 0.86171386 0.56314475]
 [0.22568127 0.01767579 0.95538962 0.10842422]]
[[0.62251652 0.62836449]
 [0.1213638  0.72174831]
 [0.49447301 0.87235929]
 [0.63240196 0.01449725]]
[[1.38699165 1.46650888]
 [0.9834478  1.14819895]
 [0.68361759 0.98958242]]
